### ISSUE TITLE
Страница раздела. При наведении на кнопку "К списку вариантов", она не меняет цвет

### ISSUE THREAD

**Issue by Popova-Anastasia** [Project-Youmath/youmath-frontend#17]
Предусловие:
Перейти на сайт 
https://youmath.ru

Шаги:

1. Перейти на главную страницу

2. Нажать "Разделы"

3. Выбрать раздел "Высшая математика для дистанционного обучения"

Ожидаемы результат:

При наведении происходит смена цвета на белый

![Image](https://github.com/Project-Youmath/youmath-frontend/assets/129196151/015da93e-6e5e-443b-ab89-57cba9c9ba08)

Фактический результат:
Смена цвета не происходит

![Image](https://github.com/Project-Youmath/youmath-frontend/assets/129196151/7f284bc2-0e67-478e-96e7-a7cc9df65201)

Окружение: Яндекс Браузер 1539*864

**Comment by LiyaVysotskaya** [comment]
Front done: 23.11.21

**Comment by SvetlanaF1** [comment]
кнопка также осталась зеленой, смена цвета не происходит

Окружение: Firefox, 1366*768


![Image](https://github.com/Project-Youmath/youmath-frontend/assets/151532643/fb548f04-56d4-40e9-9f51-b6f87590785e)

**Comment by SvetlanaF1** [comment]
проверено: Firefox, chrome

**Comment by HelenaSerkova** [comment]
окружение Яндекс Браузер и Сафари работает
