### ISSUE TITLE
Главная. Клик по одному из популярных разделов, происходит переход в футер сайта выбранного раздела

### ISSUE THREAD

**Issue by HelenaSerkova** [Project-Youmath/youmath-frontend#28]
Предусловие:
Перейти на сайт 
https://project-youmath.github.io/youmath-frontend/

Шаги:

1. Перейти на главную страницу
2. Долистать до блока "Популярные разделы"
3. Кликнуть по разделу "Высшая математика для дистанционного обучения"

Ожидаемый результат:
Происходит переход в раздел, в верхнюю часть сайта.

![Image](https://github.com/Project-Youmath/youmath-frontend/assets/73123877/e34ca1bd-1f67-4d53-85f9-3be2407b5ca5)

Фактический результат:
Происходит переход в футер выбранного раздела

![Image](https://github.com/Project-Youmath/youmath-frontend/assets/73123877/fbd235a1-e50b-4267-aca1-6952e7c908b6)

Окружение: Яндекс Браузер 1539*864

**Comment by LiyaVysotskaya** [comment]
Front done: 2023.11.23

**Comment by HelenaSerkova** [comment]
Проверено: Яндекс, Chrome, FareFox, Safari
