### ISSUE TITLE
Главная. Клик по логотипу в футере не ведет на главную страницу

### ISSUE THREAD

**Issue by HelenaSerkova** [Project-Youmath/youmath-frontend#29]
Предусловие:
Перейти на сайт 
https://project-youmath.github.io/youmath-frontend/

Шаги:

1. Перейти на главную страницу сайта
2. Спуститься в футер сайта
3. Кликнуть по логотипу

Ожидаемый результат:
Происходит переход в хэдер главной страницы сайта

![Image](https://github.com/Project-Youmath/youmath-frontend/assets/73123877/4744792d-dd24-40e0-bdb8-e1dc5b257770)

Фактический результат:
Ничего не происходит при клике на логотип

![Image](https://github.com/Project-Youmath/youmath-frontend/assets/73123877/590a7c75-d699-41c6-a778-a6e9bbd81b1a)

Окружение: Яндекс Браузер 1539*864

**Comment by LiyaVysotskaya** [comment]
Front done: 2023.11.23

**Comment by HelenaSerkova** [comment]
в окружении Яндекс Браузер 1539*864 не работает
в окружении FireFox 1366*768 работает

**Comment by SvetlanaF1** [comment]
хром - работает

**Comment by HelenaSerkova** [comment]
в Яндекс браузере заработало
