### ISSUE TITLE
Главная. При клике на кнопку "Связаться с нами" в футере сайта происходит переход в футер страницы "Обратная связь"

### ISSUE THREAD

**Issue by HelenaSerkova** [Project-Youmath/youmath-frontend#30]
Предусловие:
Перейти на сайт 
https://project-youmath.github.io/youmath-frontend/

Шаги:

1. Перейти на главную страницу
2. Долистать до футера
3. Кликнуть "Связаться с нами"

Ожидаемый результат:
Происходит переход в хэдер на страницу обратной связи

![Image](https://github.com/Project-Youmath/youmath-frontend/assets/73123877/128f2fe9-5169-42f3-ace3-b80d46caddf1)

Фактический результат:
Происходит переход в футер на страницу обратной связи

![Image](https://github.com/Project-Youmath/youmath-frontend/assets/73123877/57d196e9-66b0-4fee-a3b5-56d0e6706f6c)

Окружение: Яндекс Браузер 1539*864

**Comment by LiyaVysotskaya** [comment]
Front done: 2023.11.23

**Comment by SvetlanaF1** [comment]
проверено: firefox, хром - работает

**Comment by HelenaSerkova** [comment]
Яндекс браузер и Safary работает
