### ISSUE TITLE
Опечатка в разделе "связаться с нами"

### ISSUE THREAD

**Issue by HelenaSerkova** [Project-Youmath/youmath-frontend#35]
Предусловие:
Перейти на сайт
https://youmath.ru/

Шаги:

1. Открыть главную страницу
2. Нажать в футере ссылку "связаться с нами"
 

Ожидаемый результат:
В поле для ввода текста серая подсказка "Введите текст сообщения"

Фактический результат:
Пропущена буква

![Image](https://github.com/Project-Youmath/youmath-frontend/assets/73123877/bddae8cb-789a-4ed0-9e47-6aa8d458a2b4)

**Comment by LiyaVysotskaya** [comment]
Front done: 2023.11.25
Pull request: Fix/typo correction #45
