### ISSUE TITLE
Footer. опечатка

### ISSUE THREAD

**Issue by SvetlanaF1** [Project-Youmath/youmath-frontend#36]
Предусловие: перейти на сайт
https://youmath.ru/

Шаги:
1. Открыть главную страницу
2. Скролл до Footer

Ожидаемый результат:
Все материалы представлены на сайте исключительно с целью ознакомления читателями и не преследуют коммерческих целей или нарушение авторских прав.

Фактический результат:
Все материалы представленные на сайте исключительно с целью ознакомления читателями и не преследуют коммерческих целей или нарушение авторских прав.

Окружение: FireFox 1366*768

**Comment by SvetlanaF1** [comment]
![Image](https://github.com/Project-Youmath/youmath-frontend/assets/151532643/a4ce032e-c756-416f-b415-aaaa34469ea9)

**Comment by LiyaVysotskaya** [comment]
Front done: 2023.11.25
Pull request: Fix/typo correction https://github.com/Project-Youmath/youmath-frontend/pull/45
