### ISSUE TITLE
Опечатка в названии раздела "Высшая математика для заочного факультета"

### ISSUE THREAD

**Issue by SvetlanaF1** [Project-Youmath/youmath-frontend#39]
Предусловие:
- перейти на сайт https://youmath.ru

Шаги:
1. Открыть главную страницу
2. Тап на Разделы

Ожидаемый результат:
Высшая математика для заочного факультета

Фактический результат:

![Image](https://github.com/Project-Youmath/youmath-frontend/assets/151532643/9b626e78-b361-4370-b8e8-4bffdc92c951)

Окружение: FireFox 1366*768

**Comment by LiyaVysotskaya** [comment]
![Image](https://github.com/Project-Youmath/youmath-frontend/assets/121226479/fc1c0f5c-948b-4541-a0e4-0919480a0864)

Опечатка приходит с бэка

**Comment by smirnov-andrey** [comment]
Бек возвращает то что внесли в базу. Бек не имеет к контенту ни какого отношения и не проверяет орфографию.
