### ISSUE TITLE
Основной блок: в разделах под наименованием нет авторов учебников

### ISSUE THREAD

**Issue by ElenaVZaytseva** [Project-Youmath/youmath-frontend#40]
Предусловие:
Перейти на сайт
https://youmath.ru/

Шаги:

Открыть главную страницу

1. Прокрутить до раздела "Популярные задачи"
2. Проверить под названиями разделов наличие авторов

Ожидаемый результат:

1. Под названиями разделов прописаны авторы

![1 (2)](https://github.com/Project-Youmath/youmath-frontend/assets/151606660/3ea05266-405d-4fc8-9abf-c1251214785d)

Фактический результат:

1. Под названием учебника авторы не прописаны в некоторых разделах

![1_2](https://github.com/Project-Youmath/youmath-frontend/assets/151606660/369002a3-3f04-4238-bc03-02deacf12433)

Окружение Google Chrome 1920*1080

**Comment by ElenaVZaytseva** [comment]
Предусловие:
Перейти на сайт
https://youmath.ru/

Шаги:

Открыть главную страницу

Прокрутить до раздела "Популярные задачи"
Проверить под названиями разделов наличие авторов
Ожидаемый результат:

Под названиями разделов прописаны авторы
Фактический результат:

Авторы не прописаны в 1 и 2 разделах


Окружение Google Chrome

**Comment by LiyaVysotskaya** [comment]
![Image](https://github.com/Project-Youmath/youmath-frontend/assets/121226479/21f72609-3067-4e77-92d2-94203dd6d2d0)

Авторы приходят с бэка

**Comment by smirnov-andrey** [comment]
Ни каких авторов в базе нет. Есть заголовок и подзаголовок. Бек возвращает то что администратор внес в базу. Там где подзаголовок не указан, очевидно возвращается пустое поле. Issue не имеет к беку ни какого отношения.
